    - name: Wordpress.zip татаж байна.
      uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
      register: wp_checksum
    - name: Wordpress.zip татаж байна p2.
      get_url: url=https://wordpress.org/latest.zip dest=/var/www/wordpress.zip checksum="sha1:{{wp_checksum.content}}"
    - name: Unzip хийж байна.
      unarchive: src=/var/www/wordpress.zip dest=/var/www/ copy=no creates=/var/www/wordpress/wp-settings.php
