  - name: Copy file with owner and permissions
    command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  - name: Enabling modules
    replace:
      path: /var/www/wordpress/wp-config.php
      regexp:  'database_name_here' 
      replace: 'wordpress'
  - name: Enabling modules
    replace:
      path: /var/www/wordpress/wp-config.php
      regexp: 'username_here'
      replace: 'wordpressuser'
  - name: Enabling modules
    replace:
      path: /var/www/wordpress/wp-config.php
      regexp: 'password_here'
      replace: '%hj7Ga3r8Ftc'
