    - name: Configuring permission
      ansible.builtin.file:
        path: /var/www/wordpress
        state: directory
        recurse: yes
        owner: nginx
        group: nginx
    - name: Managing selinux
      shell: sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/wordpress(/.*)?"
    - name: Managing selinux v2
      shell: sudo restorecon -Rv /var/www/wordpress
      
