- hosts: test3
  become: true
  gather_facts: yes
  become_method: sudo
  become_user: root
  connection: ssh
  tasks:
    - name: Install certbot snap with option --classic
      community.general.snap:
        name: certbot
        classic: yes
