name: deploy ansible

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/ansible/
      with: 
        playbook: playbook.yml
